apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubernetes-event-logger.fullname" . }}-leaderelection
  labels:
    {{- include "kubernetes-event-logger.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["{{ include "kubernetes-event-logger.leaseName" . }}"]
    verbs: ["get", "update"]
