apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-event-logger.fullname" . }}
  labels:
    {{- include "kubernetes-event-logger.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsPort.containerPort }}
      targetPort: {{ .Values.metricsPort.name }}
      protocol: TCP
      name: {{ .Values.metricsPort.name }}
  selector:
    {{- include "kubernetes-event-logger.selectorLabels" . | nindent 4 }}
